### ISSUE TITLE
Upgrade `sabberworm/php-css-parser` to version 8?

### ISSUE THREAD

**Issue by ThomasLandauer** [PhenX/php-svg-lib#12]
Just being curious:  
Is there a specific reason why you're requiring version 6.0 of `sabberworm/php-css-parser` in your `composer.json`?  
Current version is 8.1 - see https://github.com/sabberworm/PHP-CSS-Parser/releases

**Comment by PhenX** [comment]
Hi !
No particular reason, I just didn't notice there were new releases :)
Did you have the occasion to test the latest version ?

**Comment by ThomasLandauer** [comment]
No, I didn't, since I'm not sure what I would be supposed to look at specifically, to be able to confirm if it's working or not :-)

**Comment by thomasgriffin** [comment]
This needs to be updated as `sabberworm/php-css-parser` v6.0 throws a fatal error in PHP7.

**Comment by benjaminprojas** [comment]
@PhenX would love to see an update for this. Any idea on an ETA?

**Comment by PhenX** [comment]
As there are no reasons not to upgrade, I did it in 06e2d40318bd32e62f33eecc46559483dd755540

**Comment by benjaminprojas** [comment]
awesome! any chance we could get a new released tagged so I can get on dompdf and have them update it there? We are using composer to pull in dompdf and need this update.  Thanks!

**Comment by kostajh** [comment]
Yes, tagging a new release would be very helpful!
