### ISSUE TITLE
Incorrect handling of "rotate" transformation with origin coordinates

### ISSUE THREAD

**Issue by hakimio** [PhenX/php-svg-lib#15]
Axis title text is positioned incorrectly when rendering following image:

[dual axis.txt](https://github.com/PhenX/php-svg-lib/files/882600/dual.axis.txt)

**Comment by hakimio** [comment]
I think the problem is that "text-anchor" -> "middle" is handled incorrectly for rotated text.

**Comment by hakimio** [comment]
Ok, "text-anchor" is just one issue. Another issue is that rotation origin point is ignored (second and third "rotate" transformation parameters)...

**Comment by hakimio** [comment]
The actual and the main reason why vertical axis labels are positioned incorrectly is that rotation origin points are ignored (second and third "rotate" transformation parameters).
I have made it work in my fork of this project:
https://github.com/hakimio/php-svg-lib
https://github.com/hakimio/dompdf

I would make a pull request, but it's been some time since I took trigonometry lessons and I am not sure how to convert rorate() method in CPdf class to do rotation clockwise instead of counter-clockwise the right way. Currently I just reverse the angle by negating it.

**Comment by naitsirch** [comment]
I have created a PR now, that fixes the issue with just touching `src/Svg/Tag/AbstractTag.php`. It's a pity that this project seem to be unmaintained :-(

@PhenX Please check the PR. It would be nice if you could merge it.

**Comment by PhenX** [comment]
Hello @naitsirch, thank you for the pull request. I agree the project is not well maintained, in fact I don't have time for it anymore...

**Comment by naitsirch** [comment]
Maybe you could find volunteers that could help you out ;-) Maybe the guys from Dompdf?

**Comment by hakimio** [comment]
@naitsirch There is only [one person](https://github.com/dompdf/dompdf/graphs/contributors) maintaining dompdf nowadays.

**Comment by naitsirch** [comment]
Okay, I see :-/
