### ISSUE TITLE
Please tag 0.3

### ISSUE THREAD

**Issue by pwolanin** [PhenX/php-svg-lib#19]
It would be great to have php 7.1 support in a real release.

Thanks!

**Comment by maps82** [comment]
I think this is necessary to also use dompdf with 7.1. Is there an ETA for 0.3?

**Comment by ThomasLandauer** [comment]
Yes, please! I'd need this fix: https://github.com/PhenX/php-svg-lib/commit/34b53c9a149cb7fd978d3d9be9879ee6607fa198
