### ISSUE TITLE
Echo causes unexpected output on recoverable error

### ISSUE THREAD

**Issue by UCIS** [PhenX/php-svg-lib#30]
The echo statement at [Document.php line 354](https://github.com/PhenX/php-svg-lib/blob/a85f7fe9fe08d093a4a8583cdd306b553ff918aa/src/Svg/Document.php#L354) causes unexpected output which may corrupt other data. Is there a better way to report such recoverable errors? As far as I can tell this is the only echo statement in the code.

**Comment by PhenX** [comment]
Fixed by 8f543ede60386faec9b0012833536de4b6083bb9
