### ISSUE TITLE
Namespace declaration statement has to be the very first statement

### ISSUE THREAD

**Issue by SnakeME** [PhenX/php-svg-lib#39]
With 0.3 everything was working fine (except the PHP 7.2 count error https://github.com/PhenX/php-svg-lib/pull/37).

With the new release 0.3.1 I'm now getting the following error:

(1/1) FatalErrorExceptionNamespace declaration statement has to be the very first statement or after any declare call in the script
--
in Document.php line 9

/vendor/phenx/php-svg-lib/src/Svg/Document.php line 9

I'm using PHP 7.2

When I switch back from 0.3.1 to 0.3 I'm getting again:

(1/1) ErrorExceptioncount(): Parameter must be an array or an object that implements Countable
--
in Document.php line 259

**Comment by PhenX** [comment]
Is it better now ?

**Comment by SnakeME** [comment]
Works like a charm! Thanks for the quick fix!
