### ISSUE TITLE
DOMPDF PHP SVG LIB USAGE

### ISSUE THREAD

**Issue by zahidaziz16** [PhenX/php-svg-lib#4]
Any example of this package usage? I already used dompdf, now have installed this package in laravel, how to use it together??

**Comment by bsweeney** [comment]
If you're using dompdf 0.7.0 or later you need do nothing more than ensure the class files are available. Currently dompdf only supports SVG embedded as an image, e.g. `<img src="tiger.svg">`.

**Comment by landsman** [comment]
I want some example about using too. I am using SVG as plain code without <img> tag.

**Comment by bsweeney** [comment]
If anyone still needs help feel free to post back but considering the age of this issue I'm closing it.
