### ISSUE TITLE
Require sabberworm/php-css-parser ^8 instead of 8.1.*

### ISSUE THREAD

**Issue by dontub** [PhenX/php-svg-lib#51]
Currently `sabberworm/php-css-parser` is required in version `8.1.*`. Is there any specific reason to disallow minor updates? If not, I would suggest to change the required version to `^8`. (The current version of `sabberworm/php-css-parser` is `8.3.0`.)

**Comment by bsweeney** [comment]
Relevant to #45

**Comment by m-bosch** [comment]
Will this me solved? I cant upgrade to Laravel 6.0 because of this issue.

**Comment by PhenX** [comment]
Fixed by #45

**Comment by m-bosch** [comment]
Thanks @PhenX are you building a new version/releasing?

**Comment by PhenX** [comment]
@m-bosch yep https://github.com/PhenX/php-svg-lib/releases/tag/v0.3.3
