### ISSUE TITLE
PHP 7.4 compatibility

### ISSUE THREAD

**Issue by humunuk** [PhenX/php-svg-lib#60]
When used with DomPDF Cpdf.php file, the scripts sets arrays ($currentLineTransparency and $currentFillTransparency) to null:
https://github.com/PhenX/php-svg-lib/blob/master/src/Svg/Surface/SurfaceCpdf.php#L394

In Cpdf it checks first if attempted mode and opacity is same as set before, this produces "Trying to access array offset on value of type null" notice in Php 7.4, because SurfadeCpdf sets those arrays to null after setting mode

**Comment by ghidoz** [comment]
The issue still occurs :(
