### ISSUE TITLE
Critical Security breach through Sabberworm (code injection)

### ISSUE THREAD

**Issue by Jany-M** [PhenX/php-svg-lib#69]
As mentioned in detail [here](https://github.com/sabberworm/PHP-CSS-Parser/issues/343), the Sabberworm library has a HUGE vulnerability and can be used to compromise critically any website.

My specific case was with a WordPress site that had malicious js injected into EVERY single .js file (core, plugins, theme).

The issue was also raised [here](https://github.com/dompdf/dompdf/issues/2573), since it uses the PHP SVG library.

**Comment by PowerKiKi** [comment]
Closing this issue to keep the discussion in a single place, https://github.com/sabberworm/PHP-CSS-Parser/issues/343, until we better understand what is going on.
